protected/controllers/ImageController.php
<?php

namespace app\controllers;

use app\components\utils\ImageUtils;
use app\models\Images;
use Imagine\Gd\Imagine;
use Imagine\Image\Box;
use Imagine\Image\Point;
use Yii;
use yii\imagine\Image;
use yii\web\Controller;
use yii\web\HttpException;

class ImageController extends Controller
{
    public function actionCreateImage()
    {
        $idPost = false;
        $ownerType = false;
        $model = false;
        $res = [];

        if (!Yii::$app->request->isAjax)
            return false;

        if(isset($_POST['id']) && !empty($_POST['id'])) $idPost = $_POST['id'];

        if(isset($_POST['type']) && !empty($_POST['type'])) $ownerType = $_POST['type'];

        if(isset($_POST['w']) && !empty($_POST['w'])) $w = $_POST['w'];
        if(isset($_POST['h']) && !empty($_POST['h'])) $h = $_POST['h'];

        if(isset($_FILES) && !empty($_FILES))
        {
            $files  = $_FILES;
            foreach ($files as $file)
            {
                if($file['type'] != 'image/jpeg' && $file['type'] != 'image/png')
                {
                    $res['error'] = 'Неправильне розширення зображення! Воно повинно бути .jpg або .png';
                    break;
                }

                if ($idPost)
                    $model = Images::findOne(['productId' => $idPost, 'productType' => $ownerType]);

                if (!$model)
                {
                    $model = new Images();
                    if ($idPost)
                        $model->ownerId = $idPost;
                    if ($ownerType)
                        $model->ownerType = $ownerType;
                }
                if($file['type'] == 'image/jpeg')
                    $model->ext = 'jpg';
                else
                    $model->ext = 'png';
                $model->timeUpdate = date('Y-m-d H:i',time());
                if($model->save())
                {
                    $imagesPath = Yii::$app->basePath.'/../res'.ImageUtils::resourceIdToDirPass($model->id);
                    if (!is_dir($imagesPath))
                        mkdir($imagesPath, 0777, true);
                    $nameAvatar=$model->id.".".$model->ext;
                    $name = $imagesPath . '/' . $nameAvatar;
                    move_uploaded_file($file['tmp_name'],$name);
                }
            }
        }

        if (empty($res))
        {
            $name = ImageUtils::genImageUrl($model->id, $model->timeUpdate, $w, $h);

            header("Content-type: application/json");
            echo json_encode(['id' => $model->id, 'src' => $name, 'error' => 'none'], JSON_UNESCAPED_UNICODE);
            Yii::$app->end();
        }
        else
        {
            header("Content-type: application/json");
            echo json_encode(['error' => $res['error']], JSON_UNESCAPED_UNICODE);
            Yii::$app->end();
        }

    }


    public function actionImage($id, $time, $slug=null, $w=null, $h=null, $ext='jpg')
    {
        $id = str_replace("/","",$id);
        $allowedAvatarSizes = ["37x37", "66x66", "50x50", "100x100", "150x200", "160x160","170x170","210x280", "300x200",
            "200x130", "300x185", "309x192", "630x384", "630x370", "1323x343","600","300","620","470x246","185x115","x620"];

        if (($w || $h)
            &&
            (
                $h!=null && !in_array("{$w}x{$h}", $allowedAvatarSizes)
                ||
                $h==null && !in_array("{$w}", $allowedAvatarSizes)
                ||
                $w==null && !in_array("x{$h}", $allowedAvatarSizes)
            )
        )
            throw new HttpException(404, "Image size not found");

//        $woteMark = !in_array("{$w}x{$h}", ["300x200", "1323x343", "630x370", "66x66", "37x37", "100x100"]);
        $woteMark = in_array("{$w}", ["620","300"]) && is_null($h)
            || in_array("{$w}x{$h}", ["470x246"]) || (!$w && !$h);
        ;
//        if (!)
//            $woteMark = true;

        $modelResource = Images::findOne(['id'=>$id]);

        if (empty($modelResource)) throw new HttpException(404, 'Image not load');

        $idPath = ImageUtils::resourceIdToDirPass($id);
        $time2 = base_convert(strtotime($modelResource->timeUpdate),10,36);
        $slug2=empty($modelResource->slug)?$modelResource->id:$modelResource->slug;

        if (!$w && !$h)
            $imageName = "{$slug2}.{$time2}.{$ext}";
        else
            $imageName = "{$slug2}.{$time2}." . ($w?"{$w}":"") . ($h?"x{$h}":"") . ".{$ext}";

        $imagesPath = Yii::$app->basePath.'/../media/res'. $idPath."/$imageName";

        if ($slug!=$slug2 || $time!=$time2)
        {
            $id2=trim(preg_replace("//","/",$id),"/");
            header("Location: /media/res/$id2/$imageName");
            die;
        }

        #print $imagesPath."<br>";

        if ( ! file_exists($imagesPath))
        {

            $imageSource = Yii::$app->basePath.'/../res'. $idPath .'/'. "$id.{$ext}";
            if (!file_exists($imageSource))
                throw new HttpException(404);

            $img = (new Imagine)->open($imageSource);

            if(!file_exists(dirname($imagesPath)))
                mkdir(dirname($imagesPath),0775, true);

            $box = $img->getSize();


            if (!$w && $h)
                $w = $h / $box->getHeight() * $box->getWidth();


            if (!$w && $box->getWidth()>1600){
                $s = 1600/$box->getWidth();
                $w = $box->getWidth()*$s;
                $h = $box->getHeight()*$s;
            }

            if ($w) {
                if ($h == null)
                    $h = $w / $box->getWidth() * $box->getHeight();

                $boxRatio = $box->getWidth() / $box->getHeight();
                $ratio = $w / $h;
                if ($boxRatio > $ratio + 1e-8) {
                    $nw = $ratio * $box->getHeight();
                    $img->crop(new Point(max(0, ($box->getWidth() - $nw) / 2), 0), new Box($nw, $box->getHeight()));
                } else if ($boxRatio < $ratio - 1e-8) {
                    $nh = 1 / $ratio * $box->getWidth();
                    $img->crop(new Point(0, max(0, ($box->getHeight() - $nh) / 2)), new Box($box->getWidth(), $nh));
                }

                $img->resize(new Box($w, $h));
            }


            if ($woteMark)
            {
                $logo = Image::getImagine()->open(\Yii::$app->basePath."/../images/watermark.png");

                if (!$w){
                    $box = $img->getSize();
                    $w = $box->getWidth();
                    $h = $box->getHeight();
                }

                $ls=$logo->getSize();

                $scale = min(0.27*$w/$ls->getWidth(), 0.27*$h/$ls->getHeight() );
                $scale = min($scale, 1.2);

                $logo->resize(new Box($ls->getWidth()*$scale, $ls->getHeight()*$scale));
                $ls=$logo->getSize();

                $img->paste($logo, new Point($w-$ls->getWidth()-5,$h-$ls->getHeight()-5));
            }

            $img->save($imagesPath,['quality'=>85]);

        }
        if ($ext == 'jpg')
            header("Content-Type: image/jpeg");
        else
            header("Content-Type: image/png");

        echo file_get_contents($imagesPath);
    }


}

protected/controllers/OrdersController.php
<?php

namespace app\controllers;

use app\components\utils\GlobalsUtils;
use app\components\utils\OrderUtils;
use app\models\form\OrdersForm;
use app\models\OrderProducts;
use app\models\Orders;
use app\models\Products;
use app\models\ProductsPrices;
use app\models\ProductsSize;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;

class OrdersController extends Controller
{

    public $layout = "//admin";

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['admin', "update", "delete", "view", "restore"],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['create', "add-price-id", "delete-price-id", "add-count"],
                        'allow' => true,
                    ],
                ],
                'denyCallback' => function () {
                    return $this->goHome();
                }
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionAdmin()
    {
        $model = Orders::find()->where(['deleted' => 0]);

        $count = $model->count();

        $dataProvider = new ActiveDataProvider ([
            'query' => $model,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 30,
            ],
        ]);

        $model1 = Orders::find()->where(['deleted' => 1])->andWhere('status IS NOT NULL');

        $count1 = $model1->count();

        $dataProvider1 = new ActiveDataProvider ([
            'query' => $model1,
            'totalCount' => $count1,
            'pagination' => [
                'pageSize' => 30,
            ],
        ]);

        return $this->render('admin', [
            'dataProvider' => $dataProvider,
            'dataProvider1' => $dataProvider1,
        ]);
    }

    public function actionView($id=null)
    {
        if (!$id)
            return $this->redirect('/admin/orders');

        $model = Orders::find()->where(['id' => $id])->one();
        $sql = "SELECT OP.count, PP.price, P.*, S.size
                FROM ProductsPrices PP
                LEFT JOIN ProductsSize S ON S.id=PP.sizeId
                LEFT JOIN Products P ON P.id=PP.productId
                LEFT JOIN OrderProducts OP ON OP.productPriceId=PP.id
                WHERE OP.orderId=".$id."
                ORDER BY OP.id";
        $count = Yii::$app->db->createCommand($sql)->queryAll();
        if (!$model && !count($count))
            return $this->redirect('/admin/orders');

        $dataProviderPrice = new SqlDataProvider ([
            'sql' => $sql,
        ]);


        return $this->render('view', [
            'dataProviderPrice' => $dataProviderPrice,
            'model' => $model,
        ]);
    }

    public function actionCreate()
    {
        $this->layout = 'main';
        $form = new OrdersForm();
        $user = Yii::$app->user->identity;

        $ip = OrdersForm::getIp();
        $userAgent = GlobalsUtils::issetdef($_SERVER["HTTP_USER_AGENT"]);
        $model = Orders::find();

        if ($user)
            $model->andWhere(['userId' => $user->Id]);
        else
            $model->andWhere('ip="'.$ip.'" AND userAgent="'.$userAgent.'" AND status IS NULL');

        $model = $model->one();
        $orders = [];

        if ($model)
        {
            $sql = "SELECT SUM(IFNULL(PP.price*OP.count,0)) as `sum`, P.name, P.type, OP.count, OP.id, PP.price, PS.size
            FROM OrderProducts OP
            LEFT JOIN ProductsPrices PP ON PP.id=OP.productPriceId
            LEFT JOIN ProductsSize PS ON PS.id=PP.sizeId
            LEFT JOIN Products P ON P.id=PP.productId
            WHERE OP.orderId=".$model->id."
            GROUP BY OP.id";
            $orders = Yii::$app->db->createCommand($sql)->queryAll();
        }

        if ($form->load(Yii::$app->request->post()) && $form->create())
                return $this->redirect('/admin/orders');

        return $this->render('create', [
            'model' => $form,
            'user' => $user,
            'main' => 'Зберегти',
            'orders' => $orders,
        ]);
    }

    public function actionUpdate($id=null)
    {
        if (!$id)
            return $this->redirect('/admin/orders');

        $model =  Orders::findOne(['id' => $id]);
        if (!$model)
            return $this->redirect('/admin/orders');

        $form = new OrdersForm();

        $form->id = $id;
        $form->userName = $model->userName;
        $form->addressId = $model->addressId;
        $form->status = $model->status;
        $form->telephone = $model->telephone;
        $form->email = $model->email;

        $sql = OrderProducts::findAll(['orderId' => $id]);

        $form->productPriceId = ArrayHelper::getColumn($sql, 'productPriceId');
        $form->count = ArrayHelper::getColumn($sql, 'count');

        if ($form->load(Yii::$app->request->post()))
        {
            $form->productPriceId = Yii::$app->request->post('OrdersForm')['productPriceId'];
            $form->count = Yii::$app->request->post('OrdersForm')['count'];

            if ($form->update())
                return $this->redirect('/admin/orders');
        }



        return $this->render('update', [
            'model' => $form,
            'main' => 'Редагувати',
        ]);
    }

    public function actionDelete($id=null)
    {
        if (!$id)
            return $this->redirect('/admin/orders');

        Orders::updateAll(['deleted' => 1], ['id' => $id]);

        return $this->redirect('/admin/orders');
    }

    public function actionRestore($id=null)
    {
        if (!$id)
            return $this->redirect('/admin/orders');

        Orders::updateAll(['deleted' => 0], ['id' => $id]);

        return $this->redirect('/admin/orders');
    }

    public function actionDeletePriceId($orderId=null, $productPriceId=null)
    {
        if(!Yii::$app->request->isAjax)
        {
            if ($orderId && $productPriceId)
                OrderProducts::deleteAll(['orderId' => $orderId, 'productPriceId' => $productPriceId]);

            return $this->redirect('/update/orders/'.$orderId);
        }

        $res = [];
        if(empty($_POST['id']))
            $res["error"]="Не вказані дані";

        if (empty($res["error"]))
        {
            $order = OrderProducts::findOne($_POST['id']);
            if ($order)
                $model = OrderProducts::findAll(['orderId' => $order->orderId]);
            if (empty($model) || empty($order))
                $res["error"] = "Не знайдене замовлення";

            if (empty($res["error"]))
            {
                $orderId = $order->orderId;
                $res['count'] = $order->count;
                $order->delete();

                $res['close'] = 'one';

                if (count($model) < 2)
                {
                    Orders::deleteAll(['id' => $orderId]);
                    $res['close'] = 'all';
                }

                $res['sum'] = OrderUtils::getSum($orderId);

                $res["status"] = "ok";
            }
        }

        header("Content-type: application/json");
        echo json_encode($res, JSON_UNESCAPED_UNICODE);
        Yii::$app->end();
    }

    public function actionAddPriceId()
    {
        if(!Yii::$app->request->isAjax)
            return false;

        $res = [];
        $res['error'] ="";
        $user = Yii::$app->user->identity;
        if(empty($_POST['productId']) || empty($_POST['sizes']))
            $res["error"]="Не вказані дані";

        $size = ProductsSize::findOne(['size' => $_POST['sizes']]);
        if (!$size)
            $res['error'] = "Неправильный розмір";

        if (empty($res["error"]))
        {
            $productPrice = ProductsPrices::findOne(['sizeId' => $size->id, 'productId' => $_POST['productId']]);
            if (!$productPrice)
                $res['error'] = "Немає такого розміру";
        }

        if (empty($res["error"]))
        {
            $res['price'] = sprintf('%.2f', $productPrice->price);
            $res['size'] = $_POST['sizes'];

            $res['add'] = 'add';

            $ip = OrdersForm::getIp();
            $userAgent = GlobalsUtils::issetdef($_SERVER["HTTP_USER_AGENT"]);
            $model = Orders::find();
            if ($userId = Yii::$app->user->getId())
                $model->andWhere(['userId' => $userId]);
            else
                $model->andWhere('ip="'.$ip.'" AND userAgent="'.$userAgent.'" AND status IS NULL');

            $model = $model->one();

            if (!$model)
            {
                $model = new Orders();
                if ($user)
                {
                    $model->userId = $user->id;
                    $model->userName = $user->name;
                    $model->telephone = $user->telephone;
                    $model->email = $user->email;
                }
                $model->ip = $ip;
                $model->userAgent = $userAgent;
                $model->save();

                $res['add'] = 'create';
            }

            if (empty($res["error"]))
            {
                $order = OrderProducts::findOne(['orderId' => $model->id, 'productPriceId' => $productPrice->id]);
                if (empty($order))
                {
                    $order = new OrderProducts();
                    $order->orderId = $model->id;
                    $order->productPriceId = $productPrice->id;
                    $order->count = 1;
                }
                else
                {

protected/views/product/create.php
<?php
/**
 * @var View $this
 * @var string $type
 * @var ProductsForm $model
 */
//$this->title = 'My Yii Application';

use app\components\utils\ImageUtils;
use app\models\form\ProductsForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

if ($type == "pizza")
{
    $this->title = 'Піца';
    $s_title = 'піци';
    $title = 'піцу';
    $w = 170;
    $h = 170;
}
elseif ($type == "kit")
{
    $this->title = 'Набори';
    $s_title = 'набору';
    $title = 'набір';
    $w = 170;
    $h = 170;
}
elseif ($type == "salad")
{
    $this->title = 'Салати';
    $s_title = 'салату';
    $title = 'салат';
    $w = 170;
    $h = 170;
}
elseif ($type == "drink")
{
    $this->title = 'Напої';
    $s_title = 'напою';
    $title = 'напій';
    $w = 170;
    $h = 170;
}
elseif ($type == "popcorn")
{
    $this->title = 'Попкорн';
    $s_title = 'попкорну';
    $title = 'попкорн';
    $w = 170;
    $h = 170;
}

$this->title = $main . ' ' . $title;

?>
<div class="project-create">
    <h1><?= $this->title ?></h1>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id')->hiddenInput() ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'data-type' => $model->type])->label('Назва '.$s_title) ?>

    <?= $form->field($model, 'ingredients')->textInput(['maxlength' => true])->label('Інгредієнти '.$s_title) ?>

    <?= $form->field($model, 'imageId')->hiddenInput()->label('Встановити картинку '.$s_title); ?>
    <label class="image-main" style="margin-bottom: 10px; cursor:pointer;">
        <?php if( ! isset($model->imageId) || empty($model->imageId)){
            echo Html::img(Url::to('/images/no-photo.png'), ['id' => 'image-product']);
        } else {
            echo Html::img(Url::to(ImageUtils::genImageUrl($model->imageId, null, $w, $h)), ['id' => 'image-product']);
        }
        ?>

        <?= Html::fileInput('image-jpg'); ?>
    </label>
    <? for ($i = 0; $i < 15; $i++):?>

        <div class="form-group <?=(empty($model->size[$i])?'hidden':'')?>">

            <?=$form->field($model, "size[$i]", ['options' => ['style' => 'width: 32%; float: left; padding-right: 2%;']])
                ->label("Розмір/Вага ".$s_title)
                ->textInput(['value' => (isset($model->size[$i])?$model->size[$i]:'')]);?>

            <?=$form->field($model, "price[$i]", ['options' => ['style' => 'width: 32%; float: left;  padding-right: 2%;']])
                ->label("Ціна ".$s_title." в грн")
                ->textInput(['value' => (isset($model->price[$i])?$model->price[$i]:'')]);?>

            <?=$form->field($model, "countMen[$i]", ['options' => ['style' => 'width: 32%; float: left;  padding: 0;']])
                ->label("Кількість людей")
                ->textInput(['value' => (isset($model->countMen[$i])?$model->countMen[$i]:'')]);?>

            <?if (isset($model->size[$i])):?>
                <?= Html::a('X', ['delete-price', 'size' => $model->size[$i], 'productId' => $model->id, 'type' => $model->type], [
                    'class' => 'btn delete-size',
                    'style' => 'margin: 24px 0 9px',
                    'data' => [
                        'confirm' => 'Ви впевнені, що хочете видалити цей розмір?',
                        'method' => 'post',
                    ],
                ]) ?>
            <?else:?>
                <div class="btn delete-product-size" data-id="<?=$i?>" style="margin: 24px 0 9px;">X</div>
            <?endif;?>
        </div>

    <?endfor;?>
    <div class="form-group">
        <?= Html::submitButton('Добавити розмір', ['class' => 'btn info bonus-from-value']) ?>
    </div>
    <div class="form-group">
        <?= Html::submitButton($main, ['class' =>'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script>
    $(function () {
        $('.form-group').on('click', '.bonus-from-value', function (e) {
            e.preventDefault();
            var form = $('.form-group');
            form.siblings('.hidden:eq(0)').removeClass('hidden');
        });

        $('.form-group').on('click', '.delete-product-size', function () {
            var form = $('.form-group'),
                index = $(this).attr('data-id');
            form.children('.field-productsform-size-'+index).addClass('hidden');
            form.children('.field-productsform-size-'+index).find('input').val('');
            form.children('.field-productsform-price-'+index).addClass('hidden');
            form.children('.field-productsform-price-'+index).find('input').val('');
            form.children('.field-productsform-countmen-'+index).addClass('hidden');
            form.children('.field-productsform-countmen-'+index).find('input').val('');
            form.children('.field-productsform-countmen-'+index).next().addClass('hidden');
        });

        $('input[name="image-jpg"]').on('change', function () {
            var type = $('#productsform-name').attr('data-type'),
                id = $('#productsform-id').val(),
                src = $('#image-product').attr('src');

            $('#image-product').attr('src', '/images/load.gif');

            var data = new FormData();
            $.each( this.files, function( key, value )
            {
                data.append(key, value);
            });
            data.append('type', type);
            data.append('id', id);
            data.append('w', <?= $w ?>);
            data.append('h', <?= $h ?>);

            $.ajax({
                url: '/image/create-image',
                type: 'POST',
                data: data,
                cache: false,
                dataType: 'json',
                processData: false,
                contentType: false
            }).done(function (data) {
                if (data.error == "none")
                {
                    $('#productsform-imageid').val(data.id);
                    $('#image-product').attr('src', data.src);
                }
                else
                {
                    alert(data.error);
                    $('#image-product').attr('src', src);
                }
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert("Невозможно загрузить: Ошибка: " + jqXHR.status + " " + jqXHR.statusText);
                $('#image-product').attr('src', src);
            });
        });
    })
</script>

protected/views/product/index.php
<?php
/**
 * @var View $this
 * @var array $model
 * @var string $type
 */
//$this->title = 'My Yii Application';

use app\components\utils\ImageUtils;
use app\models\form\ProductsForm;
use app\models\Images;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
if ($type == "pizza")
{
    $this->title = 'Піца';
    $s_title = 'піци';
    $title = 'піцу';
    $w = 170;
    $h = 170;
}
elseif ($type == "kit")
{
    $this->title = 'Набори';
    $s_title = 'набору';
    $title = 'набір';
    $w = 262;
    $h = 195;
}
elseif ($type == "salad")
{
    $this->title = 'Салати';
    $s_title = 'салату';
    $title = 'салат';
    $w = 225;
    $h = 145;
}
elseif ($type == "drink")
{
    $this->title = 'Напої';
    $s_title = 'напою';
    $title = 'напій';
    $w = 115;
    $h = 245;
}
elseif ($type == "popcorn")
{
    $this->title = 'Попкорн';
    $s_title = 'попкорну';
    $title = 'попкорн';
    $w = 150;
    $h = 200;
}

?>

<script>
    $(function () {
        $('input[type="radio"]').each(function () {
            $(this).siblings('.radio-button').toggleClass('checked', this.checked);
            if (this.checked)
            {
                var size = $(this).closest('.product-size'),
                    id = $(this).siblings('.radio-button').attr('data-id');
                size.siblings('.product-buy').find('.price').css({'display': 'none'});
                size.siblings('.product-buy').find('.price-'+id).css({'display': 'inline-block'});
            }
        });
        $(".product-size").on("change", 'input[type="radio"]', function () {
            var size = $(this).closest('.product-size'),
                id = $(this).siblings('.radio-button').attr('data-id');
            size.find('.radio-button').removeClass('checked');
            $(this).siblings('.radio-button').toggleClass('checked', this.checked);
            size.siblings('.product-buy').find('.price').css({'display': 'none'});
            size.siblings('.product-buy').find('.price-'+id).css({'display': 'inline-block'});
        });

        $('.buy').click(function () {
            var $this = $(this),
                html = $this.html(),
                product=$this.closest('.product'),
                id = $this.attr('id'),
                sizes = product.find('.radio-button.checked').attr('data-size');
            $this.attr('disabled', 'disabled');
            $.ajax({
                url: "/orders/add-price-id",
                data: {
                    sizes: sizes,
                    productId: product.attr('data-id')
                },
                type: "POST",
                dataType: 'json'
            }).done(function (data) {
                $this.attr('disabled', null);

                if (data.error !== "")
                {
                    alert(data.error);
                    $this.html(html);
                }

                else if (data.status=="ok")
                {
                    $this.html('Хочу ще');
                    $this.addClass('select');
                    $('#bucket').addClass('full');

                    if (data.add == 'create')
                    {
                        $('.bucket-hidden').find('p').remove();
                        $('.bucket-hidden').append("<div class='products-bucket'></div>" +
                            "<div class='sum-bucket'><p class='pull-left'>Сума:</p><p class='pull-right'>0 грн</p></div>"+
                            "<div class='order-bucket'><a href='<?= Url::toRoute('/orders/create') ?>'>Оформити замовлення</a></div>")
                    }

                    if (data.add == 'add' || data.add == 'create')
                    {
                        $('.bucket-hidden').find('.products-bucket').append("<div class='product-bucket' data-id='"+data.orderId+"'>"+
                            "<div class='bucket-title'><span>"+data.name+(data.size?"<br>"+data.size:"")+"</span><br>"+data.price+" грн"+
                            "</div>" +
                            "<div><div class='count-bucket'><img class='bucket-minus' src='/images/header/bucket-count.png' />" +
                            "<span>"+data.count+"</span><img class='bucket-plus' src='/images/header/bucket-count.png' /></div>" +
                            "</div><div><div class='delete-bucket'><img src='/images/header/bucket-delete.png' /></div></div></div>")
                    }
                    else
                    {
                        $('.bucket-hidden').find('.product-bucket[data-id="'+data.orderId+'"]').find('.count-bucket span').text(data.count)
                    }

                    $('.bucket-hidden').find('.sum-bucket .pull-right').text(data.sum+' грн');
                    $('.bucket').siblings('.costs').text('сума '+data.sum+' грн');
                }
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert("Невозможно добавить: Ошибка: " + jqXHR.status + " " + jqXHR.statusText);
                $this.html(html);
                $this.attr('disabled', null);
            });
        })
    })
</script>

<? $i=0 ?>
<div class="products <?= $type ?>">
    <? foreach ($model as $form):
        /**@var ProductsForm $form*/?>

        <? if ($i > 0 && $i % 3 == 0): ?>
            </div><div class="products <?= $type ?>">
        <? endif; ?>

        <div class="product" data-id="<?= $form->id ?>">
            <div class="title-product">
                <?= $form->name; ?>
            </div>

            <div class="img">
                <? $img = Images::findOne($form->imageId) ?>
                <img src="<?= $img?ImageUtils::genImageUrl($img->id, $img->timeUpdate, $w, $h):''?>">
            </div>

            <div class="desc">
                (<?= $form->ingredients; ?>)
            </div>
            <div class="product-size">
                <? if (count($form->size) > 1):?>
                    <? $j = 0;
                    foreach ($form->size as $value):?>
                    <?= Html::radio($form->id, $j == 0, [
                            "label" => "<div class='radio-button' data-id='$j' data-size='$value'>$value</div>",
                        ]) ?>
                        <? $j++;
                    endforeach; ?>
                <? elseif ($form->size): ?>
                    <div class='radio-button checked' data-size='<?= $form->size[0] ?>'><?= $form->size[0] ?></div>
                <? endif; ?>
            </div>
            <div class="product-buy">
                <? foreach ($form->price as $index=>$value):?>
                    <div class="price price-<?= $index ?>">
                        <?= $value." <span>грн</span>" ?>
                    </div>
                <? endforeach; ?>
                <div class="buy">Замовити</div>
            </div>
        </div>

    <?$i++;
    endforeach; ?>
</div>