protected/controllers/OrdersController.php
<?php

namespace app\controllers;

use app\components\utils\GlobalsUtils;
use app\components\utils\OrderUtils;
use app\models\form\OrdersForm;
use app\models\OrderProducts;
use app\models\Orders;
use app\models\Products;
use app\models\ProductsPrices;
use app\models\ProductsSize;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;

class OrdersController extends Controller
{

    public $layout = "//admin";

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['admin', "update", "delete", "view", "restore"],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['create', "add-price-id", "delete-price-id", "add-count"],
                        'allow' => true,
                    ],
                ],
                'denyCallback' => function () {
                    return $this->goHome();
                }
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionAdmin()
    {
        $model = Orders::find()->where(['deleted' => 0]);

        $count = $model->count();

        $dataProvider = new ActiveDataProvider ([
            'query' => $model,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 30,
            ],
        ]);

        $model1 = Orders::find()->where(['deleted' => 1])->andWhere('status IS NOT NULL');

        $count1 = $model1->count();

        $dataProvider1 = new ActiveDataProvider ([
            'query' => $model1,
            'totalCount' => $count1,
            'pagination' => [
                'pageSize' => 30,
            ],
        ]);

        return $this->render('admin', [
            'dataProvider' => $dataProvider,
            'dataProvider1' => $dataProvider1,
        ]);
    }

    public function actionView($id=null)
    {
        if (!$id)
            return $this->redirect('/admin/orders');

        $model = Orders::find()->where(['id' => $id])->one();
        $sql = "SELECT OP.count, PP.price, P.*, S.size
                FROM ProductsPrices PP
                LEFT JOIN ProductsSize S ON S.id=PP.sizeId
                LEFT JOIN Products P ON P.id=PP.productId
                LEFT JOIN OrderProducts OP ON OP.productPriceId=PP.id
                WHERE OP.orderId=".$id."
                ORDER BY OP.id";
        $count = Yii::$app->db->createCommand($sql)->queryAll();
        if (!$model && !count($count))
            return $this->redirect('/admin/orders');

        $dataProviderPrice = new SqlDataProvider ([
            'sql' => $sql,
        ]);


        return $this->render('view', [
            'dataProviderPrice' => $dataProviderPrice,
            'model' => $model,
        ]);
    }

    public function actionCreate()
    {
        $this->layout = 'main';
        $form = new OrdersForm();
        $user = Yii::$app->user->identity;

        $ip = OrdersForm::getIp();
        $userAgent = GlobalsUtils::issetdef($_SERVER["HTTP_USER_AGENT"]);
        $model = Orders::find();

        if ($user)
            $model->andWhere(['userId' => $user->Id]);
        else
            $model->andWhere('ip="'.$ip.'" AND userAgent="'.$userAgent.'" AND status IS NULL');

        $model = $model->one();
        $orders = [];

        if ($model)
        {
            $sql = "SELECT SUM(IFNULL(PP.price*OP.count,0)) as `sum`, P.name, P.type, OP.count, OP.id, PP.price, PS.size
            FROM OrderProducts OP
            LEFT JOIN ProductsPrices PP ON PP.id=OP.productPriceId
            LEFT JOIN ProductsSize PS ON PS.id=PP.sizeId
            LEFT JOIN Products P ON P.id=PP.productId
            WHERE OP.orderId=".$model->id."
            GROUP BY OP.id";
            $orders = Yii::$app->db->createCommand($sql)->queryAll();
        }

        if ($form->load(Yii::$app->request->post()) && $form->create())
                return $this->redirect('/admin/orders');

        return $this->render('create', [
            'model' => $form,
            'user' => $user,
            'main' => 'Зберегти',
            'orders' => $orders,
        ]);
    }

    public function actionUpdate($id=null)
    {
        if (!$id)
            return $this->redirect('/admin/orders');

        $model =  Orders::findOne(['id' => $id]);
        if (!$model)
            return $this->redirect('/admin/orders');

        $form = new OrdersForm();

        $form->id = $id;
        $form->userName = $model->userName;
        $form->addressId = $model->addressId;
        $form->status = $model->status;
        $form->telephone = $model->telephone;
        $form->email = $model->email;

        $sql = OrderProducts::findAll(['orderId' => $id]);

        $form->productPriceId = ArrayHelper::getColumn($sql, 'productPriceId');
        $form->count = ArrayHelper::getColumn($sql, 'count');

        if ($form->load(Yii::$app->request->post()))
        {
            $form->productPriceId = Yii::$app->request->post('OrdersForm')['productPriceId'];
            $form->count = Yii::$app->request->post('OrdersForm')['count'];

            if ($form->update())
                return $this->redirect('/admin/orders');
        }



        return $this->render('update', [
            'model' => $form,
            'main' => 'Редагувати',
        ]);
    }

    public function actionDelete($id=null)
    {
        if (!$id)
            return $this->redirect('/admin/orders');

        Orders::updateAll(['deleted' => 1], ['id' => $id]);

        return $this->redirect('/admin/orders');
    }

    public function actionRestore($id=null)
    {
        if (!$id)
            return $this->redirect('/admin/orders');

        Orders::updateAll(['deleted' => 0], ['id' => $id]);

        return $this->redirect('/admin/orders');
    }

    public function actionDeletePriceId($orderId=null, $productPriceId=null)
    {
        if(!Yii::$app->request->isAjax)
        {
            if ($orderId && $productPriceId)
                OrderProducts::deleteAll(['orderId' => $orderId, 'productPriceId' => $productPriceId]);

            return $this->redirect('/update/orders/'.$orderId);
        }

        $res = [];
        if(empty($_POST['id']))
            $res["error"]="Не вказані дані";

        if (empty($res["error"]))
        {
            $order = OrderProducts::findOne($_POST['id']);
            if ($order)
                $model = OrderProducts::findAll(['orderId' => $order->orderId]);
            if (empty($model) || empty($order))
                $res["error"] = "Не знайдене замовлення";

            if (empty($res["error"]))
            {
                $orderId = $order->orderId;
                $res['count'] = $order->count;
                $order->delete();

                $res['close'] = 'one';

                if (count($model) < 2)
                {
                    Orders::deleteAll(['id' => $orderId]);
                    $res['close'] = 'all';
                }

                $res['sum'] = OrderUtils::getSum($orderId);

                $res["status"] = "ok";
            }
        }

        header("Content-type: application/json");
        echo json_encode($res, JSON_UNESCAPED_UNICODE);
        Yii::$app->end();
    }

    public function actionAddPriceId()
    {
        if(!Yii::$app->request->isAjax)
            return false;

        $res = [];
        $res['error'] ="";
        $user = Yii::$app->user->identity;
        if(empty($_POST['productId']) || empty($_POST['sizes']))
            $res["error"]="Не вказані дані";

        $size = ProductsSize::findOne(['size' => $_POST['sizes']]);
        if (!$size)
            $res['error'] = "Неправильный розмір";

        if (empty($res["error"]))
        {
            $productPrice = ProductsPrices::findOne(['sizeId' => $size->id, 'productId' => $_POST['productId']]);
            if (!$productPrice)
                $res['error'] = "Немає такого розміру";
        }

        if (empty($res["error"]))
        {
            $res['price'] = sprintf('%.2f', $productPrice->price);
            $res['size'] = $_POST['sizes'];

            $res['add'] = 'add';

            $ip = OrdersForm::getIp();
            $userAgent = GlobalsUtils::issetdef($_SERVER["HTTP_USER_AGENT"]);
            $model = Orders::find();
            if ($userId = Yii::$app->user->getId())
                $model->andWhere(['userId' => $userId]);
            else
                $model->andWhere('ip="'.$ip.'" AND userAgent="'.$userAgent.'" AND status IS NULL');

            $model = $model->one();

            if (!$model)
            {
                $model = new Orders();
                if ($user)
                {
                    $model->userId = $user->id;
                    $model->userName = $user->name;
                    $model->telephone = $user->telephone;
                    $model->email = $user->email;
                }
                $model->ip = $ip;
                $model->userAgent = $userAgent;
                $model->save();

                $res['add'] = 'create';
            }

            if (empty($res["error"]))
            {
                $order = OrderProducts::findOne(['orderId' => $model->id, 'productPriceId' => $productPrice->id]);
                if (empty($order))
                {
                    $order = new OrderProducts();
                    $order->orderId = $model->id;
                    $order->productPriceId = $productPrice->id;
                    $order->count = 1;
                }
                else
                {

protected/controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\utils\ImageUtils;
use app\model\form\ChangePassForm;
use app\models\form\ProductsForm;
use app\models\form\RegisterForm;
use app\models\form\RemindPasswordForm;
use app\models\Params;
use app\models\Products;
use app\models\Users;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\form\LoginForm;
use app\models\form\ContactForm;
use yii\web\NotFoundHttpException;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $text = null;
        $text = Params::findOne(['key' => 'mainPage', 'deleted' => 0]);

        $shares = "SELECT I.*
                   FROM Services S
                   LEFT JOIN Images I ON I.id=S.imageId
                   WHERE S.deleted=0 AND S.type='share' AND I.id IS NOT NULL
                   ORDER BY timeUpdate DESC
                   LIMIT 5";

        $shares = Yii::$app->db->createCommand($shares)->queryAll();

        $pizza = [];
        $i = 0;
        $model = Products::findAll(['type' => 'pizza', 'deleted' => 0]);

        foreach ($model as $item)
        {
            /**@var Products $item */
            $pizza[$i] = new ProductsForm();

            $pizza[$i]->id = $item->id;
            $pizza[$i]->name = $item->name;
            $pizza[$i]->ingredients = $item->ingredients;
            $pizza[$i]->type = 'pizza';
            $pizza[$i]->imageId = $item->imageId;

            $sql = Yii::$app->db->createCommand("SELECT S.*, P.price
                FROM ProductsPrices P
                LEFT JOIN ProductsSize S ON S.id=P.sizeId
                WHERE S.type LIKE 'pizza' AND P.productId=".$item->id."
                ORDER BY S.size")->queryAll();

            $pizza[$i]->size = ArrayHelper::getColumn($sql, 'size');
            $pizza[$i]->price = ArrayHelper::getColumn($sql, 'price');
            $pizza[$i]->countMen = ArrayHelper::getColumn($sql, 'countMen');
            foreach ($pizza[$i]->size as $keys=>$items)
            {
                $pizza[$i]->size[$keys] = $items;
            }

            $i++;
        }

        if ($text) {
            $text = $text->value;
        }

        return $this->render('index', [
            'text' => $text,
            'shares' => $shares,
            'pizza' => $pizza,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $text = null;
        $text = Params::findOne(['key' => 'contact', 'deleted' => 0]);

        if ($text) {
            $text = $text->value;
        }

        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
            'text' => $text,
        ]);
    }

    public function actionDelivery()
    {
        $text = null;
        $text = Params::findOne(['key' => 'delivery', 'deleted' => 0]);

        if ($text) {
            $text = $text->value;
        }

        return $this->render('delivery', [
            'text' => $text,
        ]);
    }
}

protected/views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

$count = 0;

AppAsset::register($this);

$this->title = 'PizzaKP';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap" style="padding-top: 70px">

    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar-inverse admin',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Піца', 'url' => ['/admin/pizza']],
            ['label' => 'Набори', 'url' => ['/admin/kit']],
            ['label' => 'Салати', 'url' => ['/admin/salad']],
            ['label' => 'Напої', 'url' => ['/admin/drink']],
            ['label' => 'Попкорн', 'url' => ['/admin/popcorn']],
            ['label' => 'Акції', 'url' => ['/admin/share']],
            ['label' => 'Новини', 'url' => ['/admin/new']],
            ['label' => 'Відгуки', 'url' => ['/admin/reviews']],
            ['label' => 'Партнери', 'url' => ['/admin/partner']],
            ['label' => 'Замовлення', 'url' => ['/admin/orders']],
            ['label' => 'Інше редагування', 'url' => ['/admin/params']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; PizzaKP, <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

protected/views/layouts/main.php
<?php

/* @var $this \yii\web\View */

use app\components\utils\GlobalsUtils;
use app\components\utils\ParamsUtils;
use app\models\form\OrdersForm;
use app\models\Orders;
use app\models\Params;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Url;
use app\assets\AppAsset;

$start = ParamsUtils::selectParam('workStart', '00:00');
$finish = ParamsUtils::selectParam('workFinish', '23:59');
$phone = ParamsUtils::selectParam('phone', null);
$phone2 = ParamsUtils::selectParam('phone2', null);
$minOrder = ParamsUtils::selectParam('minOrder', 0);


$ip = OrdersForm::getIp();
$userAgent = GlobalsUtils::issetdef($_SERVER["HTTP_USER_AGENT"]);
$model = Orders::find();

if ($userId = Yii::$app->user->getId())
    $model->andWhere(['userId' => $userId]);
else
    $model->andWhere('ip="'.$ip.'" AND userAgent="'.$userAgent.'" AND status IS NULL');

$model = $model->one();
$orders = [];
if ($model)
{
    $sql = "SELECT SUM(IFNULL(PP.price*OP.count,0)) as `sum`, P.name, P.type, OP.count, OP.id, PP.price, PS.size
            FROM OrderProducts OP
            LEFT JOIN ProductsPrices PP ON PP.id=OP.productPriceId
            LEFT JOIN ProductsSize PS ON PS.id=PP.sizeId
            LEFT JOIN Products P ON P.id=PP.productId
            WHERE OP.orderId=".$model->id."
            GROUP BY OP.id";
    $orders = Yii::$app->db->createCommand($sql)->queryAll();
}

if (!empty($orders))
{
    $count = ArrayHelper::getColumn($orders, 'sum');
    $count = array_sum($count);
}
$count = !empty($count)?$count:0;

AppAsset::register($this);

$this->title = 'PizzaTime';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <div class="container">
        <div class="raw">
            <div class="col-md-3 col-header-logo">
                <div><a href="/"><img src="/images/header/logo.png" class="logo"></a></div>
            </div>
            <div class="raw-mobile">
            <div class="col-md-4 col-xs-6 col-header">
                <div id="phone">
                    <?if ($phone || $phone2):?>
                        <img src="/images/header/phone.png">
                    <?endif;?>
                    <?= $phone?$phone:'' ?>
                    <?if ($phone && $phone2):?>
                        <div class="point"></div>
                    <?endif;?>
                    <?= $phone2?$phone2:'' ?>
                </div>
                <div id="call-back">Мінімальне замовлення <span class="number-color"><?= $minOrder ?></span> грн</div>
            </div>
            <div class="col-md-3 col-xs-6 col-header">
                <div>
                    <?= Yii::$app->user->isGuest ? (
                        Html::beginForm(['#'], 'post', ['class' => 'navbar-form'])
                        . Html::a('Реєстрація', [Url::toRoute('/register')],
                            [
                                'class' => 'btn btn-link',
                                'style' => 'border-right: 1px solid #F6511D',
                            ]
                        )
                        . Html::a('Вхід', [Url::toRoute('/site/login')],
                            ['class' => 'btn btn-link']
                        )
                        . Html::endForm()
                    ) : (
                        Html::beginForm(['/logout'], 'post', ['class' => 'navbar-form'])
                        . Html::submitButton('Вихід (' . Yii::$app->user->identity->name . ')',
                            (Yii::$app->user->can('admin')?
                                ['class' => 'btn btn-link', 'style' => 'border-right: 1px solid #F6511D']
                                : ['class' => 'btn btn-link'])
                        )
                        .(Yii::$app->user->can('admin')?Html::a('Адмінка', ['/product/admin', 'type' => 'pizza'],
                            [
                                'class' => 'btn btn-link',
                            ]
                        ):'')
                        . Html::endForm()
                    )
                    ?>
                </div>


                <div id="orders">Приймаємо замовлення з <span class="number-color"><?= $start ?></span> до <span class="number-color"><?= $finish ?></span></div>
            </div>
            </div>
            <div class="col-md-2 col-header">
                <div class="costs">сума <?= sprintf('%.2f', $count) ?> грн</div>
                <div class="bucket">
                    <div id="bucket" class="<?= $count > 0?'full':'' ?>">
                        Кошик
                        <?= file_get_contents(Yii::$app->basePath . '/../images/header/bucket.svg')?>
                    </div>
                    <div class="bucket-hidden hidden">
                        <img src="/images/header/logo-bucket.png" />
                        <? if ($count > 0): ?>
                            <div class="products-bucket">
                                <? foreach ($orders as $order): ?>
                                    <div class="product-bucket" data-id="<?= $order['id'] ?>">
                                        <div class="bucket-title">
                                            <span><?= $order['name'] . ($order['size']?'<br>'.$order['size']:'') ?></span><br><?= sprintf('%.2f', $order['price']) ?> грн
                                        </div>
                                        <div>
                                            <div class="count-bucket">

                                                <img class="bucket-minus" src="/images/header/bucket-count.png" />
                                                <span><?= $order['count'] ?></span>
                                                <img class="bucket-plus" src="/images/header/bucket-count.png" />
                                            </div>
                                        </div>
                                        <div>
                                            <div class="delete-bucket">
                                                <img src="/images/header/bucket-delete.png" />
                                            </div>
                                        </div>
                                    </div>
                                <? endforeach; ?>
                            </div>
                            <div class="sum-bucket">
                                <p class="pull-left">Сума:</p>
                                <p class="pull-right"><?= sprintf('%.2f', $count) ?> грн</p>
                            </div>
                            <div class="order-bucket">
                                <a href="<?= Url::toRoute('/orders/create') ?>">Оформити замовлення</a>
                            </div>
                        <? else: ?>
                            <p>Кошик пустий</p>
                        <? endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar-inverse',
        ],
    ]);

    $items[] = ['label' => 'Піца', 'url' => ['/product/index', 'type' => 'pizza']];
    $items[] = ['label' => 'Набори', 'url' => ['/product/index', 'type' => 'kit']];
    $items[] = ['label' => 'Салати', 'url' => ['/product/index', 'type' => 'salad']];
    $items[] = ['label' => 'Напої', 'url' => ['/product/index', 'type' => 'drink']];
    $items[] = ['label' => 'Попкорн', 'url' => ['/product/index', 'type' => 'popcorn']];
    $items[] = ['label' => 'Доставка', 'url' => ['/site/delivery']];
    $items[] = ['label' => 'Акції', 'url' => ['/services/index', 'type' => 'share']];
    $items[] = ['label' => 'Контакти', 'url' => ['/site/contact']]; ?>

    <?= Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $items,
        'activateParents'=>true,
    ]); ?>

    <?NavBar::end(); ?>

    <div class="container" style="margin: 70px auto 30px">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">Найшвидша доставка піци в місті &copy; <?= date('Y') ?></p>
        <p class="pull-right">Приєднуйтесь до нас
            <a><img src="/images/footer-logo/vk.png" /></a>
            <a><img src="/images/footer-logo/instagram.png" /></a>
            <a><img src="/images/footer-logo/facebook.png" /></a>
        </p>
        <p class="pull">
            <a href="<?= Url::toRoute('/delivery')?>">Доставка</a>
            <a href="<?= Url::toRoute('/contact')?>">Контакти</a>
            <a href="<?= Url::toRoute('/partner')?>">Партнери</a>
            <a href="<?= Url::toRoute('/reviews')?>">Відгуки</a>
        </p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

<script>
    $(function () {
        $('#bucket').click(function () {
            $(this).siblings('.bucket-hidden').toggleClass('hidden');
        });

        $('.bucket-hidden').on('click', '.count-bucket img', function () {
            var $this = $(this),
                id = $this.closest('.product-bucket').attr('data-id'),
                factor,
                count = $this.siblings('span').text();

            if ($this.attr('class') == 'bucket-minus')
            {
                factor = -1;
            }
            else
            {
                factor = 1;
            }

            if (count != 1 || factor != -1)
            {


                $.ajax({
                    url: "/orders/add-count",
                    data: {
                        id: id,
                        factor: factor
                    },
                    type: "POST",
                    dataType: 'json'
                }).done(function (data) {
                    if (data.error)
                    {
                        alert(data.error);
                    }
                    else if (data.status=="ok") {
                        $this.siblings('span').text(data.count);
                        $this.closest('.bucket-hidden').find('.sum-bucket .pull-right').text(data.sum+' грн');
                        $this.closest('.bucket').siblings('.costs').text('сума '+data.sum+' грн');
                    }
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert("Невозможно сохранить: Ошибка: " + jqXHR.status + " " + jqXHR.statusText);
                });
            }
        });

        $('.bucket-hidden').on('click', '.delete-bucket img', function () {
            var $this = $(this),
                id = $this.closest('.product-bucket').attr('data-id');

            $.ajax({
                url: "/orders/delete-price-id",
                data: {
                    id: id
                },
                type: "POST",
                dataType: 'json'
            }).done(function (data) {
                if (data.error)
                {
                    alert(data.error);
                }
                else if (data.status=="ok")
                {
                    $this.closest('.bucket-hidden').find('.sum-bucket .pull-right').text(data.sum+' грн');
                    $this.closest('.bucket').siblings('.costs').text('сума '+data.sum+' грн');

                    if (data.close == 'one')
                        $this.closest('.product-bucket').remove();
                    else
                    {
                        $this.closest('.bucket-hidden').siblings('div').removeClass('full');
                        $this.closest('.products-bucket').siblings('div').remove();
                        $this.closest('.products-bucket').replaceWith('<p>Кошик пустий</p>');
                    }
                }
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert("Невозможно сохранить: Ошибка: " + jqXHR.status + " " + jqXHR.statusText);
            });
        });

        var height = $('.navbar-inverse').offset().top;

        if ($(this).scrollTop() + 10 >= height)
        {
            $('.navbar-inverse').css({
                'position': 'fixed',
                'top': '10px'
            });
        }

        $(document).scroll(function () {
            if ($(this).scrollTop() + 10 >= height)
            {
                $('.navbar-inverse').css({
                    'position': 'fixed',
                    'top': '10px'
                });
            }

            if ($(this).scrollTop() + 10 < height)
            {
                $('.navbar-inverse').css({
                    'position': 'absolute',
                    'top': height+'px',
                });
            }

        })
    })
</script>